# Variables
BUILD_DIR=.builds

GO_BIN_DIR := $(shell go env GOPATH|cut -d ":" -f 1)/bin
GO_SRC_EXT = .go
GO_SRC_FILES = $(shell find . $(PKG_PATH) -name \*${GO_SRC_EXT})
GO_OS = $(shell go env GOOS)
GO_ARCH = $(shell go env GOARCH)
CLI_NAME = immich-go
COVERAGE_FILE = coverage.out
BINARY_NAME = $(BUILD_DIR)/$(CLI_NAME)
BINARY_NAME_WIN = $(BUILD_DIR)/win/$(CLI_NAME).exe
BINARY_NAME_LINUX = $(BUILD_DIR)/linux/$(CLI_NAME)
BINARY_NAME_MACOS_ARM = $(BUILD_DIR)/macos/arm64/$(CLI_NAME)
BINARY_NAME_MACOS_I386 = $(BUILD_DIR)/macos/i386/$(CLI_NAME)

GO_LDFLAGS := -s -w

define make_binary
	@echo "\033[32m-- Building application binary $(1) for $(2)-$(3)\033[0m"
	CGO_ENABLED=0 GOOS=$(2) GOARCH=$(3) go build -ldflags "$(GO_LDFLAGS)" -v -o $(1) main.go
endef

# Default target
.PHONY: all
all: test binary

$(BINARY_NAME): $(GO_SRC_FILES)
	$(call make_binary, $(BINARY_NAME),$(GO_OS),$(GO_ARCH))
.PHONY: binary
binary: $(BINARY_NAME)  ## Build application binary (native)

$(BINARY_NAME_WIN): $(GO_SRC_FILES)
	$(call make_binary,$@,windows,amd64)
.PHONY: binary_win
binary_win: $(BINARY_NAME_WIN)   ## Build application binary for Windows

$(BINARY_NAME_LINUX): $(GO_SRC_FILES)
	$(call make_binary,$@,linux,amd64)
.PHONY: binary_linux
binary_linux: $(BINARY_NAME_LINUX)   ## Build application binary for Linux

$(BINARY_NAME_MACOS_ARM): $(GO_SRC_FILES)
	$(call make_binary,$@,darwin,arm64)
$(BINARY_NAME_MACOS_I386): $(GO_SRC_FILES)
	$(call make_binary,$@,darwin,amd64)
.PHONY: binary_macos
binary_macos: $(BINARY_NAME_MACOS_ARM) $(BINARY_NAME_MACOS_I386)   ## Build application binaries for MacOS

.PHONY: install
install: binary   ## Install the native binary into GOBIN
	@echo "\033[32m-- Installing native binary in $(GO_BIN_DIR)\033[0m"
	@mv $(BINARY_NAME) $(GO_BIN_DIR)/$(CLI_NAME)

.PHONY: run
run: install  ## Run the application
	$(GO_BIN_DIR)/$(CLI_NAME)

.PHONY: test
test:  ## Run unit tests
	@echo "\033[32m-- Running unittests for immich-cli \033[0m"
	go test --race -v -count=1 -coverprofile=$(COVERAGE_FILE) ./...
	@echo "-- Test coverage for immich-cli --"
	@go tool cover -func=$(COVERAGE_FILE)|grep "total:"

.PHONY: clean
clean:  ## Clean up artifacts generated by make
	@echo "\033[32m-- Cleaning immich-go\033[0m"
	@rm -rf $(BUILD_DIR)/
	@find . -name $(COVERAGE_FILE) -exec rm -f {} \;
	@rm -rf $(GO_BIN_DIR)/$(CLI_NAME)

.PHONY: fmt
fmt:  ## Format Go code
	go fmt ./...

.PHONY: lint
lint:  ## Run Go linter on code
	golangci-lint run

.PHONY: deps
deps:  ## Install Go dependencies
	go mod tidy
	go mod download

.PHONY: help
help:
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
